#!/usr/bin/python3
import rclpy
from  rclpy.node import Node
from geometry_msgs.msg import Pose


def main():
    rclpy.init()
    globalGoalPub= globalGoalPublisher()


    # Start infinite loop
    rclpy.spin(globalGoalPub)
    # Clean everything and switch the light off
    globalGoalPub.destroy_node()
    rclpy.shutdown()

class globalGoalPublisher(Node):
    def __init__(self):
        super().__init__('localgoalTF')
        self.global_goal=Pose()
        self.declare_parameter('x_global',0.0)
        self.declare_parameter('y_global',0.0)

        #Pubs
        self._pubGlobalPose= self.create_publisher(
            Pose, '/moveto/globalgoal', 10
        )
        # Node Attribute:
        self.local_frame= 'base_link'
        self.create_timer(0.1, self.publish_goal)

    #Process funcs
    def publish_goal(self):
        globalPose=Pose()
        x_global= self.get_parameter('x_global').value 
        y_global= self.get_parameter('y_global').value
        globalPose.position.x = x_global
        globalPose.position.y = y_global
        self._pubGlobalPose.publish(globalPose)


if __name__ == '__main__':
    main()
    