#!/usr/bin/python3
import rclpy
from  rclpy.node import Node
from geometry_msgs.msg import Pose
from std_msgs.msg import Bool,Int16
def main():
    rclpy.init()
    opNode= operatorNode()
    # Start infinite loop
    rclpy.spin(opNode)
    # Clean everything and switch the light off
    opNode.destroy_node()
    rclpy.shutdown()

class operatorNode(Node):
    def __init__(self):
        super().__init__('operator_node')
        self.declare_parameter('activated',False)
        #Pubs
        self._pubOPstatus= self.create_publisher(
            Bool, '/is_operator_mode', 10
        )
        # Node Attribute:
        self.create_timer(0.1, self.publish_goal)

    #Process funcs
    def publish_goal(self):
        message=Bool()
        message.data=self.get_parameter('activated').value
        self._pubOPstatus.publish(message)


if __name__ == '__main__':
    main()
    