#!/usr/bin/python3
import rclpy
from  rclpy.node import Node
from sensor_msgs.msg import LaserScan
from geometry_msgs.msg import Twist,Pose
from std_msgs.msg import Bool
import sys
import scan_echo
from math import sin,atan2,sqrt
from time import time,sleep
import random as rd

# Ros Node process:
def main():
    # Initialize ROS and a ROS node
    rclpy.init(args=sys.argv)
    node= Node( 'basic_move' )

    # Initialize our control:
    control= StraightCtrl()
    control.initializeRosNode( node )

    # Infinite Loop:
    rclpy.spin( node )

    # Clean end
    node.destroy_node()
    rclpy.shutdown()

    # Note : Positive = left

# Ros Node Class:
class StraightCtrl :
    def initializeRosNode(self, rosNode ):
        # Initialization                                           
        # Get logger from the node:
        self._logger = rosNode.get_logger()
        #scan states
        self.obstacle_right_close=False
        self.obstacle_left_close=False
        self.obstacle_right_far=False
        self.obstacle_left_far=False
        self.obstacle_full_left_far=False
        self.obstacle_full_right_far=False
        self.no_scan=True

        #init commandes 
        self.previous_z=0.5
        self.previous_x=0.15
        #init topics
        self.cmd_robot_topic=''
        self.scan_robot_topic=''
        #init function states variables
        self._emergency_stop=False
        self.random_turning=False
        self.move_to_command=False
        self.is_operator_mode=False
        #init localGoal
        self.localGoal=Pose()
        self.localGoal.position.x=0
        self.localGoal.position.y=0
        self.theta_goal=atan2(self.localGoal.position.y,self.localGoal.position.x)
        self.distance_goal=sqrt(self.localGoal.position.y**2+self.localGoal.position.x**2)

        #declare parameter to read
        rosNode.declare_parameter('is_simulation',True)
        rosNode.declare_parameter('tunnel_vision_width',0.50)
        rosNode.declare_parameter('time_step_random_turn',20)
        #read the parameters
        self.is_simulation=rosNode.get_parameter('is_simulation').value
        self.tunnel_vision_width=rosNode.get_parameter('tunnel_vision_width').value
        self.time_step_random_turn=rosNode.get_parameter('time_step_random_turn').value

        #simulation check
        if not self.is_simulation:
            global WheelDropEvent, ButtonEvent
            from kobuki_ros_interfaces.msg import WheelDropEvent, ButtonEvent
            cmd_robot_topic='/multi/cmd_nav'
            scan_robot_topic='/scan'
        else:
            cmd_robot_topic='/cmd_vel'
            scan_robot_topic='/scan'#'/base_scan' depend version de stage ou du simulateur

        # Initialize publisher:
        self._pubVelocity= rosNode.create_publisher(
            Twist, cmd_robot_topic, 10
        )
        # Initialize subscribers
        self._subToLocalGoal= rosNode.create_subscription(
            Bool, "/is_pathfinding_on_move_to" ,
            self.move_to_sub, 10
        )
        self._subToLocalGoal= rosNode.create_subscription(
            Bool, "/is_operator_mode" ,
            self.op_mode_sub, 10
        )
        self._subToLocalGoal= rosNode.create_subscription(
            Pose, "/moveto/localgoal" ,
            self.local_goal_msg, 10
        )
        if not self.is_simulation:                                                                         #if the robot is tested in real life
            self.sub_bouton=rosNode.create_subscription(ButtonEvent,'events/button',self.button,10)
            self._subToWheelDrop= rosNode.create_subscription(
                WheelDropEvent, '/events/wheel_drop',
                self.wheel_drop, 10
            )
        self._subToScan= rosNode.create_subscription(                                                 #in all cases
            LaserScan,scan_robot_topic ,
            self.scan_callback, 10
        )

        # Initialize control callback:
        self._timForCtrl= rosNode.create_timer(
            0.05, self.global_control
        )
        self._randomTurn= rosNode.create_timer(
            self.time_step_random_turn, self.random_turn
        )

    #Subs functions
    def move_to_sub(self,msg):
        self.move_to_command=msg.data

    def op_mode_sub(self,msg):
        self.is_operator_mode=msg.data

    def local_goal_msg(self,msg):
        self.localGoal=msg
        print("LocalGoal:")
        print("x:"+str(self.localGoal.position.x)+"y:"+str(self.localGoal.position.y))
        self.theta_goal=atan2(self.localGoal.position.y,self.localGoal.position.x)
        self.distance_goal=sqrt(self.localGoal.position.y**2+self.localGoal.position.x**2)
        print('theta_goal:'+str(self.theta_goal))

    def scan_callback(self, scanMsg ):
        #self._logger.info( '> get scan' )
        self.process_scan_data(scanMsg)
        #urgent stop
    
    def wheel_drop(self,msg):
        # if msg.state==0:
        #     self._emergency_stop=False
        if msg.state==1:
            velocity=Twist()
            velocity.linear.x = 0.0 #m/s
            velocity.angular.z = 0.0 #rad/s
            self._pubVelocity.publish(velocity)
            self._emergency_stop=True

    def button(self,msg):
        if msg.state == 1:
            self._emergency_stop=False

    #================================================================#
    # Definition of the position of the obstacle from the LIDAR data #
    #================================================================#
    def process_scan_data(self,scanMsg):
        #Initialization
        self.obstacle_right_close=False
        self.obstacle_left_close=False
        self.obstacle_right_far=False
        self.obstacle_left_far=False
        self.obstacle_full_left_far=False
        self.obstacle_full_right_far=False
        self.goal_straight_line_obstacle=True
        self.goal_obstacle_right_far=True
        self.goal_obstacle_left_far=True
        self.totalmindistance=100
        self.maxdistance=0
        self.mindistance=100
        self.full_right_min=100
        self.full_left_min=100
        # The robot looks in a 40cm tunnel in front of him
        scan_tunnel_d=self.tunnel_vision_width

        if scanMsg is not None : 
            self.no_scan=False
            angle= scanMsg.angle_min
            if self.move_to_command: self.find_obstacles_to_goal(scanMsg) #if move to , add some scanning
            for aDistance in scanMsg.ranges :

                #for each distance received we look if the obstacle is in the tunnel in front the robot and if so, where it is (right, left, far, close)    
                if 0.1 < aDistance:
                    if aDistance < 1.1 :
                        if self.totalmindistance>aDistance:self.totalmindistance=aDistance
                        if aDistance<0.35:
                            if angle <0 and angle >-1.35:
                                self.obstacle_right_close=True
                            if angle >0 and angle <1.35:
                                self.obstacle_left_close=True
                        else:
                            if angle <0 and angle >-1:
                                if scan_tunnel_d/(2*sin(-angle))>=aDistance:
                                    self.obstacle_right_far=True
                                    if self.maxdistance<aDistance: self.maxdistance=aDistance
                                    if self.mindistance>aDistance: self.mindistance=aDistance   
                            if angle >0 and angle <1:
                                if scan_tunnel_d/(2*sin(angle))>=aDistance:
                                    self.obstacle_left_far=True
                                    if self.maxdistance<aDistance: self.maxdistance=aDistance
                                    if self.mindistance>aDistance: self.mindistance=aDistance

                    #we also look if there are obstacles at 90 degres on each side of the robot
                    if aDistance<3:
                        if angle<-1.39 and angle >-1.55:
                            self.obstacle_full_right_far=True
                            if self.full_right_min>aDistance:self.full_right_min=aDistance
                        if angle>1.39 and angle <1.55:
                            self.obstacle_full_left_far=True
                            if self.full_left_min>aDistance:self.full_left_min=aDistance
                angle+= scanMsg.angle_increment
        else : 
            self.no_scan=True
            print("Scan not found, exit")

    def find_obstacles_to_goal(self,scanMsg):
        self.goal_straight_line_obstacle=False
        self.goal_obstacle_right_far=False
        self.goal_obstacle_left_far=False
        in_range=False
        angle= scanMsg.angle_min
        for aDistance in scanMsg.ranges:
            if 0.1 < aDistance:
                if self.theta_goal >scanMsg.angle_min+0.785398 and self.theta_goal <scanMsg.angle_max-0.785398 :
                    #Check if theta_goal is somewhere in range and find between which increment
                    if self.theta_goal>angle and self.theta_goal < angle+scanMsg.angle_increment:
                        self.theta_goal=angle
                        in_range=True # Goal is in the scan angle range
                        #Check if there is an obstacle before the goal on the straight line
                        if aDistance<self.distance_goal:
                            self.goal_straight_line_obstacle=True
                        #Check for obstacle around the straight line
                        angle_goal=scanMsg.angle_min
                        for aDistance_goal in scanMsg.ranges:
                            if 0.1 < aDistance_goal and aDistance_goal<self.distance_goal:
                                if angle_goal <self.theta_goal and angle_goal >self.theta_goal-1.5708:
                                    if (self.tunnel_vision_width+10)/(2*sin(abs(angle_goal)))>=aDistance_goal:
                                        self.goal_obstacle_right_far=True
                                if angle_goal >self.theta_goal and angle_goal <self.theta_goal+1.5708:
                                    if (self.tunnel_vision_width+10)/(2*sin(abs(angle_goal)))>=aDistance_goal:
                                        self.goal_obstacle_left_far=True
                            angle_goal+=scanMsg.angle_increment
            angle+= scanMsg.angle_increment
        if not in_range:
            print("goal is not aligned with scan range")
            self.goal_straight_line_obstacle=True
        else: print("goal is in range")

    ######################
    # robot control #
    ######################

    def global_control(self):
        if not self.is_operator_mode:
            if self.move_to_command:
                self.control_callback_move_to()
            else:self.control_callback()
    #for random reactive
    def control_callback(self):
        #Reactive reaction to environment
        if not self.random_turning:                                                        #if the robot isn't in a random turn
            #self._logger.info( '< define control' )
            velocity=Twist()
            velocity.angular.z = self.previous_z #rad/s
            base_angular_speed=0.7                                                         #rotation speed
            message=""

            #=================================#
            # First case : nothing is scanned #
            #=================================#
            if self.no_scan or self._emergency_stop:                                       #if nothing is scanned, the robot stop
                print("no scan/emergency stop")
                velocity.linear.x = 0.0 #m/s
                velocity.angular.z = 0.0 #rad/s

            #======================================#
            # Second case : something is too close #
            #======================================#
            elif self.totalmindistance<0.15:                                                #if an object is too close, the robot can only rotate on itself
                message+="object to close, turning around\n"
                velocity.linear.x = 0.0 #m/s
                velocity.angular.z  = 0.5

            #=================================#
            # Third case : something is close #
            #=================================#
            elif self.obstacle_right_close or self.obstacle_left_close:                     #something is close
                #We look at the situation (where are the obstacles) and we choose where to move

                # 1) something is close both on the right and on the left
                if self.obstacle_right_close and self.obstacle_left_close:                  
                    message+="state3:close obstacle both directions\n"

                    # is there an obstacle 90° far ?
                    if self.obstacle_full_left_far and not self.obstacle_full_right_far:    #also there is something far on the right but not on the left
                        message+="choosed to go right\n"                                    #so the robot go to the right
                        velocity.angular.z = -base_angular_speed #rad/s 
                    if self.obstacle_full_right_far and not self.obstacle_full_left_far:    #also there is something far on the left but not on the right
                        message+="choosed to go left\n"                                     #so the robot go to the left
                        velocity.angular.z=base_angular_speed
                    #We adapt our speed to the current one
                    if velocity.angular.z==0:                                               #if its the first turn and there is not one far side triggered, the robot go to the left
                        velocity.angular.z=base_angular_speed                  
                    
                    velocity.linear.x=self.smooth_speed_target(0.0,0.02)
                    
                # 2) something is close on the right but not on the left    
                elif self.obstacle_right_close and not self.obstacle_left_close:
                    message+="state1:close obstacle right\n"

                    #We adapt our speed to the current one
                    velocity.linear.x=self.smooth_speed_target(0.0,0.02)

                    #is there something far on the left ?    
                    if not self.obstacle_full_left_far:                                      #if not the robot turn to the left
                        velocity.angular.z = base_angular_speed #rad/s
                    if velocity.angular.z==0:
                        velocity.angular.z=base_angular_speed

                # 3) something is close on the left but not on the right        
                elif self.obstacle_left_close and not self.obstacle_right_close:
                    message+="state2:close obstacle left\n"

                    #We adapt our speed to the current one              
                    velocity.linear.x=self.smooth_speed_target(0.0,0.02)

                    #is there something far on the right ?     
                    if not self.obstacle_full_right_far:                                     #if not the robot turn to the right
                        velocity.angular.z = -base_angular_speed #rad/s
                    if velocity.angular.z==0:
                        velocity.angular.z=-base_angular_speed

                if velocity.linear.x<0.0:velocity.linear.x=0.0                               #avoiding errors

            #================================#
            # Fourth case : something is far #
            #================================#
            elif self.obstacle_right_far or self.obstacle_left_far:
                #We look at the situation (where are the obstacles) and we choose where to move

                # 1) something is far on the right but not on the left  
                if self.obstacle_right_far and not self.obstacle_left_far:
                    message+="state4:far obstacle right\n"

                    #the robot goes to the linear speed of 0.2 smoothly
                    velocity.linear.x=self.smooth_speed_target(0.2,0.02)

                    #the angle is adapted to the distance (the closer the obstacle is, the greater is the angle)
                    velocity.angular.z = -0.83*self.mindistance+1.45 #rad/s                    the robot goes to the left
    
                # 2) something is far on the left but not on the right  
                elif self.obstacle_left_far and not self.obstacle_right_far:
                    message+="state5:far obstacle left\n"

                    #the robot goes to the linear speed of 0.2 smoothly
                    velocity.linear.x=self.smooth_speed_target(0.2,0.02)

                    #the angle is adapted to the distance (the closer the obstacle is, the greater is the angle)
                    velocity.angular.z = -(-0.83*self.mindistance+1.45) #rad/s                   the robot goes to the right

                # 3) something is far both on the right and the left
                
                elif self.obstacle_right_far and self.obstacle_left_far:
                    message+="state6:far obstacle both directions\n"

                    #there is something at 90 degres on the left and not on the right
                    if self.obstacle_full_left_far and not self.obstacle_full_right_far:
                        velocity.angular.z = -base_angular_speed #rad/s                            the robot goes to the right
                    
                    #there is something at 90 degres on the right and not on the left
                    if self.obstacle_full_right_far and not self.obstacle_full_left_far:
                        velocity.angular.z=base_angular_speed #rad/s                               the robot goes to the left

                    #there is something at 90 degres on the right and the left
                    if self.obstacle_full_right_far and self.obstacle_full_left_far:
                        if self.full_right_min<self.full_left_min:
                            velocity.angular.z=base_angular_speed #rad/s                           the robot goes to the left
                        else:
                            velocity.angular.z = -base_angular_speed #rad/s                        the robot goes to the right
                    velocity.linear.x=self.smooth_speed_target(0.15,0.03)
                    #the robot goes to the linear speed of 0.15 smoothly
                    
            #===================================#
            # Fifth case : no obstacle in front #
            #===================================#
            else:
                #the robot goes forward
                velocity.angular.z = 0.0#rad/s
                velocity.linear.x=self.smooth_speed_target(0.7,0.02)
                message+="state 0:no obstacles\n"

            #previous values
            self.previous_z=velocity.angular.z
            self.previous_x=velocity.linear.x
            #publishing
            self._pubVelocity.publish(velocity)

            #=============================#
            # Print the current situation #
            #=============================#
            #printing if there are obstacles and where and the current linear and rotative speeds
            message+=str(self.obstacle_left_far)+","+str(self.obstacle_right_far)+"\n"+str(self.obstacle_left_close)+","+str(self.obstacle_right_close)+"\n"+str(self.obstacle_full_left_far)+","+str(self.obstacle_full_right_far)+"\n"+"speed:"+str(self.previous_x)+"    rotation:"+str(self.previous_z)

            print("#----------------#")
            print(message)
            print("|----------------|")
    #for move to
    def control_callback_move_to(self):
        #Reactive reaction to environment
        if not self.random_turning:                                                        #if the robot isn't in a random turn
            #self._logger.info( '< define control' )
            velocity=Twist()
            velocity.angular.z = self.previous_z #rad/s
            base_angular_speed=0.7                                                         #rotation speed
            message=""

            #=================================#
            # First case : nothing is scanned #
            #=================================#
            if self.no_scan or self._emergency_stop:                                       #if nothing is scanned, the robot stop
                print("no scan/emergency stop")
                velocity.linear.x = 0.0 #m/s
                velocity.angular.z = 0.0 #rad/s

            elif self.distance_goal<0.1:
                print('goal atteint')
                velocity.linear.x = 0.0 #m/s
                velocity.angular.z = 0.0 #rad/s                                                #the robot stop              

            #======================================#
            # Second case : something is too close #
            #======================================#
            elif self.totalmindistance<0.15:                                                #if an object is too close, the robot can only rotate on itself
                message+="object to close, turning around\n"
                velocity.linear.x = 0.0 #m/s
                velocity.angular.z  = 0.5

            #=================================#
            # Third case : something is close #
            #=================================#
            elif self.obstacle_right_close or self.obstacle_left_close:                     #something is close
                #We look at the situation (where are the obstacles) and we choose where to move

                # 1) something is close both on the right and on the left
                if self.obstacle_right_close and self.obstacle_left_close:                  
                    message+="state3:close obstacle both directions\n"

                    # is there an obstacle 90° far ?
                    if self.obstacle_full_left_far and not self.obstacle_full_right_far:    #also there is something far on the right but not on the left
                        message+="choosed to go right\n"                                    #so the robot go to the right
                        velocity.angular.z = -base_angular_speed #rad/s 
                    if self.obstacle_full_right_far and not self.obstacle_full_left_far:    #also there is something far on the left but not on the right
                        message+="choosed to go left\n"                                     #so the robot go to the left
                        velocity.angular.z=base_angular_speed
                    #We adapt our speed to the current one
                    if velocity.angular.z==0:                                               #if its the first turn and there is not one far side triggered, the robot go to the left
                        velocity.angular.z=base_angular_speed                  
                    
                    velocity.linear.x=self.smooth_speed_target(0.0,0.025)
                    
                # 2) something is close on the right but not on the left    
                elif self.obstacle_right_close and not self.obstacle_left_close:
                    message+="state1:close obstacle right\n"

                    #We adapt our speed to the current one
                    velocity.linear.x=self.smooth_speed_target(0.0,0.025)

                    #is there something far on the left ?    
                    if not self.obstacle_full_left_far:                                      #if not the robot turn to the left
                        velocity.angular.z = base_angular_speed #rad/s
                    if velocity.angular.z==0:
                        velocity.angular.z=base_angular_speed

                # 3) something is close on the left but not on the right        
                elif self.obstacle_left_close and not self.obstacle_right_close:
                    message+="state2:close obstacle left\n"

                    #We adapt our speed to the current one              
                    velocity.linear.x=self.smooth_speed_target(0.0,0.02)

                    #is there something far on the right ?     
                    if not self.obstacle_full_right_far:                                     #if not the robot turn to the right
                        velocity.angular.z = -base_angular_speed #rad/s
                    if velocity.angular.z==0:
                        velocity.angular.z=-base_angular_speed

                if velocity.linear.x<0.0:velocity.linear.x=0.0                               #avoiding errors

            #================================#
            # Fourth case : something is far #
            #================================#
            elif self.obstacle_right_far or self.obstacle_left_far:
                #We look at the situation (where are the obstacles) and we choose where to move

                # 1) something is far on the right but not on the left  
                if self.obstacle_right_far and not self.obstacle_left_far:
                    message+="state4:far obstacle right\n"

                    #the robot goes to the linear speed of 0.2 smoothly
                    velocity.linear.x=self.smooth_speed_target(0.2,0.02)

                    #the angle is adapted to the distance (the closer the obstacle is, the greater is the angle)
                    velocity.angular.z = -0.83*self.mindistance+1.45 #rad/s                    the robot goes to the left
    
                # 2) something is far on the left but not on the right  
                elif self.obstacle_left_far and not self.obstacle_right_far:
                    message+="state5:far obstacle left\n"

                    #the robot goes to the linear speed of 0.2 smoothly
                    velocity.linear.x=self.smooth_speed_target(0.2,0.02)

                    #the angle is adapted to the distance (the closer the obstacle is, the greater is the angle)
                    velocity.angular.z = -(-0.83*self.mindistance+1.45) #rad/s                   the robot goes to the right

                # 3) something is far both on the right and the left
                
                elif self.obstacle_right_far and self.obstacle_left_far:
                    message+="state6:far obstacle both directions\n"

                    #there is something at 90 degres on the left and not on the right
                    if self.obstacle_full_left_far and not self.obstacle_full_right_far:
                        velocity.angular.z = -base_angular_speed #rad/s                            the robot goes to the right
                    
                    #there is something at 90 degres on the right and not on the left
                    if self.obstacle_full_right_far and not self.obstacle_full_left_far:
                        velocity.angular.z=base_angular_speed #rad/s                               the robot goes to the left

                    #there is something at 90 degres on the right and the left
                    if self.obstacle_full_right_far and self.obstacle_full_left_far:
                        if self.full_right_min<self.full_left_min:
                            velocity.angular.z=base_angular_speed #rad/s                           the robot goes to the left
                        else:
                            velocity.angular.z = -base_angular_speed #rad/s                        the robot goes to the right
                    velocity.linear.x=self.smooth_speed_target(0.15,0.03)
                    #the robot goes to the linear speed of 0.15 smoothly
            
            #===============================================#
            # Fifth case : the goal can be reached directly #
            #===============================================#
            elif not (self.goal_straight_line_obstacle or self.goal_obstacle_right_far or self.goal_obstacle_left_far):#si rien vers le goal
                message+="state7 : le goal est libre d'accès\n"
                message+="capteur vers goal"+str(self.goal_obstacle_left_far)+str(self.goal_straight_line_obstacle)+str(self.goal_obstacle_right_far)+"\n"
                if abs(self.theta_goal)>0.08726: #si pas bien oriente
                    velocity.angular.z = self.orientate_to_goal() #s'oriente vers le goal
                    velocity.linear.x = self.smooth_speed_target(0.0,0.02) #m/s
                    message+="le goal n'est pas directement en face, turning on himself\n"
                else:#si bien oriente
                    velocity.linear.x=self.smooth_speed_target(self.speed_to_goal(self.distance_goal),0.02)#go vers le goal
                    message+="le goal est en face, going forward\n"
    
            #===================================#
            # Fifth case : no obstacle in front #
            #===================================#
            else:
                #the robot goes forward
                velocity.angular.z = self.orientate_to_goal()#rad/s
                velocity.linear.x=self.smooth_speed_target(0.6,0.012)
                message+="state 0:no obstacles\n"
                #previous values

            self.previous_z=velocity.angular.z
            self.previous_x=velocity.linear.x
            #publishing
            self._pubVelocity.publish(velocity)

            #=============================#
            # Print the current situation #
            #=============================#
            #printing if there are obstacles and where and the current linear and rotative speeds
            message+=str(self.obstacle_left_far)+","+str(self.obstacle_right_far)+"\n"+str(self.obstacle_left_close)+","+str(self.obstacle_right_close)+"\n"+str(self.obstacle_full_left_far)+","+str(self.obstacle_full_right_far)+"\n"+"speed:"+str(self.previous_x)+"    rotation:"+str(self.previous_z)

            #the message is printed only if it is different from the previous one
            print("#----------------#")
            print(message)
            print("|----------------|")

    # speed function, with the previous x and z stored variables
    def smooth_speed_target(self,target:float,step:float):
        velocity=Twist()
        if self.previous_x>target+15*step:                                          #if the robot was moving fast, it slows hardly
            velocity.linear.x=self.previous_x -step*2
        elif self.previous_x>target+step:                                            #if the robot was moving slow, its slow softly
            velocity.linear.x=self.previous_x -step
        elif self.previous_x<target-step:
            velocity.linear.x=self.previous_x +step
        else:                                                                   #if the robot was not moving, it continue
            velocity.linear.x=target
        return(velocity.linear.x)
    
    #random turn functions callback
    def random_turn(self):
        if not self._emergency_stop and not self.move_to_command :
            velocity=Twist()
            self.random_turning=True
            direction=rd.randint(1,2)         #définition de si le virage se fera à gauche ou à droite
            angle_value=rd.randint(30,180)    #angle du virage (entre 30 et 180)
            if direction==1:angle=-angle_value
            if direction==2:angle=angle_value
            while self.previous_x>0.0 and not self._emergency_stop:
                velocity.linear.x=self.smooth_speed_target(0.0,0.03)
                self.previous_x=velocity.linear.x
                self._pubVelocity.publish(velocity)
            print("Tour aléatoire : je commence un tour d'un angle de"+str(angle)+"degrès")
            self.turn_by_given_angle(angle,0.7)
            while self.previous_x<0.1 and not self._emergency_stop:
                velocity.linear.x=self.smooth_speed_target(0.5,0.02)
                self.previous_x=velocity.linear.x
                self._pubVelocity.publish(velocity)
            self.random_turning=False

    def turn_by_given_angle(self,deg,angular_speed):
        velocity=Twist()
        deg_per_sec=angular_speed*180/3.14
        duration=abs(deg/deg_per_sec) - 0.25
        if deg<0:
            rotation_speed=-angular_speed
        else:
            rotation_speed=angular_speed
        start = time()
        counter=0
        while counter < duration and not self._emergency_stop: 
            velocity.angular.z = rotation_speed
            counter = time()-start
            #Previous values
            self.previous_z=velocity.angular.z
            #Publish
            self._pubVelocity.publish(velocity)

    #goal consign function helper
    def speed_to_goal(self,distance):
        speed=distance*0.7
        if speed>0.7:speed=0.7
        if distance <0.05:speed=0
        return(speed)

    def orientate_to_goal(self):
        precision=0.08726
        if self.theta_goal>precision*3:
            rad_speed=0.7
        elif self.theta_goal<-precision*3:
            rad_speed=-0.7
    
        elif self.theta_goal>precision:
            rad_speed=0.3
        elif self.theta_goal<-precision:
            rad_speed=-0.3
        else:
            rad_speed=0.0
        return(rad_speed)
       
# Go:
if __name__ == '__main__' :
    main()