#!/usr/bin/python3
import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist
#from test_move import stop_mov
#test
def listen():
    # Initialize ROS node with ROS client
    rclpy.init()
    aNode= Node( "listener" )
    listener= ROSBumperListener(aNode)
    # Start infinite loop
    rclpy.spin(aNode)
    # Clean everything and switch the light off
    aNode.destroy_node()
    rclpy.shutdown()

class ROSBumperListener():

    def __init__(self, rosNode):
        self._logger= rosNode.get_logger()
        self._subscription= rosNode.create_subscription(
            
            pkg-tbot/kobuki_ros_interfaces/msg/BumperEvent, '/events/bumper',
            self.listener_callback, 10
        )

    def listener_callback(self, msg):
        self._logger.info( 'I heard: ' + msg.data)
    
    #def urgent_stop():
        #stop_mov(2)
    
if __name__ == '__main__':
    listen()