#!/usr/bin/python3
import rclpy
from rclpy.node import Node
from kobuki_ros_interfaces.msg import BumperEvent
from move_robot import stop_mov
#test
def listen():
    # Initialize ROS node with ROS client
    rclpy.init()
    aNode= Node( "listener" )
    listener= ROSBumperListener(aNode)
    # Start infinite loop
    rclpy.spin(aNode)
    # Clean everything and switch the light off
    aNode.destroy_node()
    rclpy.shutdown()

class ROSBumperListener():

    def __init__(self, rosNode):
        self._logger= rosNode.get_logger()
        self._subscription= rosNode.create_subscription(
            BumperEvent, '/events/bumper',
            self.listener_callback, 10
        )

    def listener_callback(self, msg):
        self._logger.info( 'I heard: ' + str(msg.state))
        if msg.state==1:
            urgent_stop()    
    def urgent_stop():
        stop_mov(2)
    
if __name__ == '__main__':
    listen()