#!/usr/bin/python3
import rclpy
from  rclpy.node import Node
from sensor_msgs.msg import LaserScan
from geometry_msgs.msg import Twist
import sys
import scan_echo
from move_robot import stop_mov, move_metre, move_degre

# Ros Node process:
def main():
    # Initialize ROS and a ROS node
    rclpy.init(args=sys.argv)
    node= Node( 'basic_move' )

    # Initialize our control:
    control= StraightCtrl()
    control.initializeRosNode( node )

    # infinite Loop:
    rclpy.spin( node )

    # clean end
    node.destroy_node()
    rclpy.shutdown()

# Ros Node Class:
class StraightCtrl :
    def initializeRosNode(self, rosNode ):
        # Get logger from the node:
        self._logger= rosNode.get_logger()
        self.obstacle_right_close=False
        self.obstacle_left_close=False
        self.obstacle_right_far=False
        self.obstacle_left_far=False
        self.no_scan=True
        self.step=0
        # Initialize publisher:
        self._pubVelocity= rosNode.create_publisher(
            Twist, '/multi/cmd_nav', 10
        )

        # Initialize scan callback:
        self._subToScan= rosNode.create_subscription(
            LaserScan, '/scan',
            self.scan_callback, 10
        )

        # Initialize control callback:
        self._timForCtrl= rosNode.create_timer(
            0.05, self.control_callback
        )

    def scan_callback(self, scanMsg ):
        self._logger.info( '> get scan' )
        self.process_scan_data(scanMsg)


    def control_callback(self):
        self._logger.info( '< define control' )
        velocity=Twist()
        velocity.angular.z = 0.5 #rad/s
        changMouv = 0
        if self.no_scan:
            print("no scan")
            self.step = 0
            velocity.linear.x = 0.0 #m/s
            velocity.angular.z = 0.0 #rad/s
            self._pubVelocity.publish(velocity)
        elif self.obstacle_right_close and not self.obstacle_left_close:
            print("close obstacle right")
            self.step = 0
            #move_degre(-5)
            velocity.linear.x = 0.0 #m/s
            velocity.angular.z = 0.5 #rad/s
            self._pubVelocity.publish(velocity)
        elif self.obstacle_left_close and not self.obstacle_right_close:
            print("close obstacle left")
            self.step = 0
            #move_degre(5)
            velocity.linear.x = 0.0 #m/s
            velocity.angular.z = -0.5 #rad/s
            self._pubVelocity.publish(velocity)
        elif self.obstacle_right_close and self.obstacle_left_close:
            print("close obstacle both directions")
            self.step = 0
            #move_degre(5)
            velocity.linear.x = 0.0 #m/s
            self._pubVelocity.publish(velocity)
        elif self.obstacle_right_far and not self.obstacle_left_far:
            print("far obstacle right")
            self.step = 0
            #move_degre(-5)
            velocity.linear.x = 0.15 #m/s
            velocity.angular.z = 0.5 #rad/s
            self._pubVelocity.publish(velocity)
        elif self.obstacle_left_far and not self.obstacle_right_far:
            print("far obstacle left")
            self.step = 0
            #move_degre(5)
            velocity.linear.x = 0.15 #m/s
            velocity.angular.z = -0.5 #rad/s
            self._pubVelocity.publish(velocity)
        elif self.obstacle_right_far and self.obstacle_left_far:
            print("far obstacle both directions")
            self.step = 0
            #move_degre(5)
            velocity.linear.x = 0.1 #m/s
            self._pubVelocity.publish(velocity)
        else:
            self.forward_smooth_accel()
            print("no obstacles")
            self.step += 1
        print("done")
       
    def process_scan_data(self,scanMsg):
        self.obstacle_right_close=False
        self.obstacle_left_close=False
        self.obstacle_right_far=False
        self.obstacle_left_far=False
        if scanMsg is not None : 
            self.no_scan=False
            angle= scanMsg.angle_min
            for aDistance in scanMsg.ranges :
                if 0.1 < aDistance and aDistance < 1 :
                    if aDistance<0.5:
                        if angle <0 and angle >-1:
                            self.obstacle_right_close=True
                        if angle >0 and angle <1:
                            self.obstacle_left_close=True
                    else:
                        if angle <0 and angle >-1:
                            self.obstacle_right_far=True
                        if angle >0 and angle <1:
                            self.obstacle_left_far=True
                angle+= scanMsg.angle_increment
        else : 
            self.no_scan=True
            print("Scan not found, exit")

    def forward_smooth_accel(self):
        velocity_array=[0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.25,0.25,0.3,0.3,0.3,0.3,
        0.35,0.35,0.4,0.4,0.4,0.4,0.4,0.4,0.4,0.4,0.4,0.4,0.45,0.45,0.5,0.5,0.5,0.5,0.5,
        0.55,0.55,0.6,0.6,0.6,0.6,0.6,0.6,0.6,0.6,0.6,0.65,0.65,0.65,0.7,0.7,0.7,0.7,0.7,
        0.75,0.75,0.75,0.8,0.8,0.8,0.8,0.8,0.8,0.8,0.8,0.8,0.8,0.8,0.8,0.8,0.85,0.9,0.9,1.0]
        if self.step >= len(velocity_array):
            self.step = len(velocity_array) - 1
        velocity=Twist()
        print(self.step)
        velocity.linear.x = velocity_array[self.step] #m/s
        velocity.angular.z = 0.0#rad/s
        self._pubVelocity.publish(velocity)
# Go:
if __name__ == '__main__' :
    main()