#!/usr/bin/python3
import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist
from time import time
from move_robot_simul import stop_mov, move_metre, move_degre
### PATH TO EXECUTE
def path():
     # Initialize ROS node with ROS client
    rclpy.init()
    # Parcours à executer
    move_metre(1)
    move_degre(90)
    move_metre(1)
    move_degre(90)
    move_metre(1)
    move_degre(90)
    move_metre(1)
    move_degre(90)
    stop_mov(10)
    # Clean everything and switch the light off
    rclpy.shutdown()

# Execute the function.
if __name__ == "__main__":
    print("test_move :: START...")
    path()
    print("move finished")

