#!/usr/bin/python3
import rclpy
from  rclpy.node import Node
from geometry_msgs.msg import Pose
from std_msgs.msg import Bool,Int16,String
def main():
    rclpy.init()
    opNode= operatorNode()
    # Start infinite loop
    rclpy.spin(opNode)
    # Clean everything and switch the light off
    opNode.destroy_node()
    rclpy.shutdown()

class operatorNode(Node):
    def __init__(self):
        super().__init__('operator_node')
        # Declaration of parameters
        self.declare_parameter('manual_teleop',False)
        self.declare_parameter('show_map_prct',False)
        self.declare_parameter('show_pathfinding_msgs',False)
        #Pubs
        self._pubOPstatus= self.create_publisher(
            Bool, '/is_manual_mode', 10
        )
        # Node Attribute:
        self.create_timer(0.1, self.publish_goal)
        #Subs
        self._subMapPrct= self.create_subscription(
                Int16, '/map_prct_discovered',
                self.map_prct_sub, 10
            )
        self._subPathfindingMsg= self.create_subscription(
                String, '/pathfinding_msg',
                self.path_msg_sub, 10
            )
    #Subs functions
    def map_prct_sub(self,msg):
        # Gets and show the map prct if the parameter is activated
        if self.get_parameter('show_map_prct').value:
            self.get_logger().info( f'Pourcentage découvert:{msg.data}')
    def path_msg_sub(self,msg):
        # Gets and show pathfinding node msgs if the parameter is activated
        if self.get_parameter('show_pathfinding_msgs').value:
            self.get_logger().info( f'{msg.data}')
    #Pub functions
    def publish_goal(self):
        # Publish the state of manual teleop parameter, it will be read by pathfinding to ajdust its behaviour
        message=Bool()
        message.data=self.get_parameter('manual_teleop').value
        self._pubOPstatus.publish(message)
        




if __name__ == '__main__':
    main()
    
