#!/usr/bin/python3
import rclpy
from  rclpy.node import Node
from sensor_msgs.msg import LaserScan
from geometry_msgs.msg import Twist,Pose
from std_msgs.msg import Bool,String
import sys
import scan_echo
from math import sin,atan2,sqrt
from time import time,sleep
import random as rd

# Ros Node process:
def main():
    # Initialize ROS and a ROS node
    rclpy.init(args=sys.argv)
    node= Node( 'basic_move' )

    # Initialize our control:
    control= StraightCtrl()
    control.initializeRosNode( node )

    # Infinite Loop:
    rclpy.spin( node )

    # Clean end
    node.destroy_node()
    rclpy.shutdown()

    # Note : Positive = left

# Ros Node Class:
class StraightCtrl :
    def initializeRosNode(self, rosNode ):
        # Initialization                                           
        # Get logger from the node:
        self._logger = rosNode.get_logger()
        # Scan states
        self.obstacle_right_close=False
        self.obstacle_left_close=False
        self.obstacle_right_far=False
        self.obstacle_left_far=False
        self.obstacle_full_left_far=False
        self.obstacle_full_right_far=False
        self.no_scan=True

        # Init commandes 
        self.previous_z=0.5
        self.previous_x=0.15
        # Init topics
        self.cmd_robot_topic=''
        self.scan_robot_topic=''
        # Init function states variables
        self._emergency_stop=False
        self.random_turning=False
        self.move_to_command=False
        self.manual_mode=False
        self.already_stopped=False
        # Init localGoal
        self.localGoal=Pose()
        self.localGoal.position.x=0
        self.localGoal.position.y=0
        self.theta_goal=atan2(self.localGoal.position.y,self.localGoal.position.x)
        self.distance_goal=sqrt(self.localGoal.position.y**2+self.localGoal.position.x**2)

        # Declare parameter to read
        rosNode.declare_parameter('is_simulation',True)
        rosNode.declare_parameter('tunnel_vision_width',0.50)
        rosNode.declare_parameter('time_step_random_turn',20)
        # Read the parameters
        self.is_simulation=rosNode.get_parameter('is_simulation').value
        self.tunnel_vision_width=rosNode.get_parameter('tunnel_vision_width').value
        self.time_step_random_turn=rosNode.get_parameter('time_step_random_turn').value

        # Simulation check
        if not self.is_simulation:
            global WheelDropEvent, ButtonEvent,Led
            from kobuki_ros_interfaces.msg import WheelDropEvent, ButtonEvent,Led
            #subs needing the kobuki_ros_interfaces
            self.sub_bouton=rosNode.create_subscription(ButtonEvent,'events/button',self.button,10)
            self._subToWheelDrop= rosNode.create_subscription(
                WheelDropEvent, '/events/wheel_drop',
                self.wheel_drop, 10
            )
            #pubs needing the kobuki_ros_interfaces
            self._pubLed=rosNode.create_publisher(Led,'commands/led1',10)
            led=Led()
            led.value=0
            self._pubLed.publish(led)
            cmd_robot_topic='/multi/cmd_nav'
            scan_robot_topic='/scan'
        else:
            cmd_robot_topic='/cmd_vel'
            scan_robot_topic='/scan'#'/base_scan' depend version de stage ou du simulateur

        # Initialize publisher:
        self._pubVelocity= rosNode.create_publisher(
            Twist, cmd_robot_topic, 10
        )
        self._pubLoggerMsg= rosNode.create_publisher(
            String, '/pathfinding_msg', 10
        )
        # Initialize subscribers
        self._subToLocalGoal= rosNode.create_subscription(
            Bool, "/is_pathfinding_on_move_to" ,
            self.move_to_sub, 10
        )
        self._subToLocalGoal= rosNode.create_subscription(
            Bool, "/is_manual_mode" ,
            self.manual_mode_sub, 10
        )
        self._subToLocalGoal= rosNode.create_subscription(
            Pose, "/moveto/localgoal" ,
            self.local_goal_msg, 10
        )
        self._subToScan= rosNode.create_subscription(                                                 #in all cases
            LaserScan,scan_robot_topic ,
            self.scan_callback, 10
        )

        # Initialize control callback:
        self._timForCtrl= rosNode.create_timer(
            0.05, self.global_control
        )
        self._randomTurn= rosNode.create_timer(
            self.time_step_random_turn, self.random_turn
        )

    ##################
    # Subs functions #
    ##################

    def move_to_sub(self,msg):
        self.move_to_command=msg.data

    def manual_mode_sub(self,msg):
        self.manual_mode=msg.data
        print(self.manual_mode)
        if self.manual_mode and not self.already_stopped:
            velocity=Twist()
            #previous values
            self.previous_z=0
            self.previous_x=0
            #publishing
            self._pubVelocity.publish(velocity)
            self.already_stopped=True
        if not self.manual_mode:
            self.already_stopped=False

    def local_goal_msg(self,msg):
        self.localGoal=msg
        #print("LocalGoal:")
        #print("x:"+str(self.localGoal.position.x)+"y:"+str(self.localGoal.position.y))
        self.theta_goal=atan2(self.localGoal.position.y,self.localGoal.position.x)
        self.distance_goal=sqrt(self.localGoal.position.y**2+self.localGoal.position.x**2)
        #print('theta_goal:'+str(self.theta_goal))

    def scan_callback(self, scanMsg ):
        self.process_scan_data(scanMsg)
    
    def wheel_drop(self,msg):
        if msg.state==1:
            led=Led()
            led.value=3
            velocity=Twist()
            velocity.linear.x = 0.0 #m/s
            velocity.angular.z = 0.0 #rad/s
            self._pubVelocity.publish(velocity)
            self._pubLed.publish(led)
            self._emergency_stop=True

    # When a button is pushed, the emergency stop status is removed
    def button(self,msg):
        if msg.state == 1:
            self._emergency_stop=False
            led=Led()
            led.value=0
            self._pubLed.publish(led)

    #================================================================#
    # Definition of the position of the obstacle from the LIDAR data #
    #================================================================#

    def process_scan_data(self,scanMsg):
        #Initialization
        self.obstacle_right_close=False
        self.obstacle_left_close=False
        self.obstacle_right_far=False
        self.obstacle_left_far=False
        self.obstacle_full_left_far=False
        self.obstacle_full_right_far=False
        self.goal_straight_line_obstacle=True
        self.goal_obstacle_right_far=True
        self.goal_obstacle_left_far=True
        self.totalmindistance=100
        self.totalmindistance_left=100
        self.totalmindistance_right=100
        self.maxdistance=0
        self.mindistance=100
        self.full_right_min=100
        self.full_left_min=100

        # If there is a scan
        if scanMsg is not None : 
            self.no_scan=False
            angle= scanMsg.angle_min
            if self.move_to_command: self.find_obstacles_to_goal(scanMsg) #if move to , add some scanning
            for aDistance in scanMsg.ranges :
                # For each distance received we look if the obstacle is in the tunnel in front the robot and if so, where it is (right, left, far, close)   
                if 0.05 < aDistance:
                    if angle <0 and angle >-1.5:
                        if self.totalmindistance_right>aDistance:self.totalmindistance_right=aDistance
                    if angle >0 and angle <1.5:
                        if self.totalmindistance_left>aDistance:self.totalmindistance_left=aDistance
                if 0.09 < aDistance:
                    if aDistance < 1.1 :
                        if self.totalmindistance>aDistance:self.totalmindistance=aDistance
                        if aDistance<0.35:
                            if angle <0 and angle >-1.35:
                                self.obstacle_right_close=True
                            if angle >0 and angle <1.35:
                                self.obstacle_left_close=True
                        else:        # The robot looks in a tunnel in front of him
                            if angle <0 and angle >-1:
                                if self.tunnel_vision_width/(2*sin(-angle))>=aDistance:
                                    self.obstacle_right_far=True
                                    if self.maxdistance<aDistance: self.maxdistance=aDistance
                                    if self.mindistance>aDistance: self.mindistance=aDistance   
                            if angle >0 and angle <1:
                                if self.tunnel_vision_width/(2*sin(angle))>=aDistance:
                                    self.obstacle_left_far=True
                                    if self.maxdistance<aDistance: self.maxdistance=aDistance
                                    if self.mindistance>aDistance: self.mindistance=aDistance

                    # We also look if there are obstacles at 90 degres on each side of the robot
                    if aDistance<3:
                        if angle<-1.39 and angle >-1.55:
                            self.obstacle_full_right_far=True
                            if self.full_right_min>aDistance:self.full_right_min=aDistance
                        if angle>1.39 and angle <1.55:
                            self.obstacle_full_left_far=True
                            if self.full_left_min>aDistance:self.full_left_min=aDistance
                angle+= scanMsg.angle_increment
        else :    # If no scan
            self.no_scan=True

    # Looking for the obstacles between the robot and the goal
    def find_obstacles_to_goal(self,scanMsg):
        self.goal_straight_line_obstacle=False
        self.goal_obstacle_right_far=False
        self.goal_obstacle_left_far=False
        in_range=False
        angle= scanMsg.angle_min
        for aDistance in scanMsg.ranges:
            if 0.1 < aDistance:
                if self.theta_goal >scanMsg.angle_min+0.785398 and self.theta_goal <scanMsg.angle_max-0.785398 :
                    #Check if theta_goal is somewhere in range and find between which increment
                    if self.theta_goal>angle and self.theta_goal < angle+scanMsg.angle_increment:
                        self.theta_goal=angle
                        in_range=True # Goal is in the scan angle range
                        #Check if there is an obstacle before the goal on the straight line
                        if aDistance<self.distance_goal:
                            self.goal_straight_line_obstacle=True
                        #Check for obstacle around the straight line
                        angle_goal=scanMsg.angle_min
                        for aDistance_goal in scanMsg.ranges:
                            if 0.1 < aDistance_goal and aDistance_goal<self.distance_goal:
                                if angle_goal <self.theta_goal and angle_goal >self.theta_goal-1.5708:
                                    if (self.tunnel_vision_width+10)/(2*sin(abs(angle_goal)))>=aDistance_goal:
                                        self.goal_obstacle_right_far=True
                                if angle_goal >self.theta_goal and angle_goal <self.theta_goal+1.5708:
                                    if (self.tunnel_vision_width+10)/(2*sin(abs(angle_goal)))>=aDistance_goal:
                                        self.goal_obstacle_left_far=True
                            angle_goal+=scanMsg.angle_increment
            angle+= scanMsg.angle_increment
        if not in_range:
            self.goal_straight_line_obstacle=True

    #################
    # Robot control #
    #################

    #~~~~~~~~~~~~~~~~~~~~~~~#
    # If no goal is defined #
    #~~~~~~~~~~~~~~~~~~~~~~~#

    def global_control(self):
        if not self.manual_mode:
            if self.move_to_command:
                self.control_callback_move_to()
            else:self.control_callback()
            
            log_msg=String()
            log_msg.data=self.log_msg_data
            self._pubLoggerMsg.publish(log_msg)

            
    #for random reactive
    def control_callback(self):
        #Reactive reaction to environment
        if not self.random_turning:                                                         #if the robot isn't in a random turn
            #self._logger.info( '< define control' )
            velocity=Twist()
            velocity.angular.z = self.previous_z #rad/s
            base_angular_speed=0.7                                                          #rotation speed
            message="\n#----------------#\n"

            #=================================#
            # First case : nothing is scanned #
            #=================================#
            if self.no_scan or self._emergency_stop:                                        #if nothing is scanned, the robot stop
                message+="no scan/emergency stop\n"
                velocity.linear.x = 0.0 #m/s
                velocity.angular.z = 0.0 #rad/s

            #======================================#
            # Second case : something is too close #
            #======================================#
            elif self.totalmindistance<0.2:                                                #if an object is too close, the robot can only rotate on itself
                message+="object to close, turning around\n"
                velocity.linear.x = 0.0 #m/s
                velocity.angular.z  = self.smooth_z_speed_target(0.5,0.1)
            elif self.totalmindistance_right<0.25 and self.totalmindistance_left<0.25:
                velocity.linear.x= self.smooth_x_speed_target(-0.2,0.02)
                velocity.angular.z  = 0.0
            elif self.totalmindistance_right<0.25:
                message+="object to close on the right, turning around on the left\n"
                velocity.linear.x = 0.0 #m/s
                velocity.angular.z  = self.smooth_z_speed_target(0.5,0.1)
            elif self.totalmindistance_left<0.25:
                message+="object to close on the left, turning around on the right\n"
                velocity.linear.x = 0.0 #m/s
                velocity.angular.z  = self.smooth_z_speed_target(-0.5,0.1)
            #=================================#
            # Third case : something is close #
            #=================================#
            elif self.obstacle_right_close or self.obstacle_left_close:                     #something is close
                #We look at the situation (where are the obstacles) and we choose where to move
                # 1) something is close both on the right and on the left
                if self.obstacle_right_close and self.obstacle_left_close:                  
                    message+="state3:close obstacle both directions:"

                    # is there an obstacle 90° far ?
                    if self.obstacle_full_left_far and not self.obstacle_full_right_far:    #also there is something far on the right but not on the left
                        message+="choosed to go right\n"                                    #so the robot go to the right
                        velocity.angular.z = self.smooth_z_speed_target(-base_angular_speed,0.1) #rad/s 
                    if self.obstacle_full_right_far and not self.obstacle_full_left_far:    #also there is something far on the left but not on the right
                        message+="choosed to go left\n"                                     #so the robot go to the left
                        velocity.angular.z=self.smooth_z_speed_target(base_angular_speed,0.1)
                    #We adapt our speed to the current one
                    if velocity.angular.z==0:                                               #if its the first turn and there is not one far side triggered, the robot go to the left
                        velocity.angular.z=self.smooth_z_speed_target(base_angular_speed,0.1)                  
                    
                    velocity.linear.x=self.smooth_x_speed_target(0.0,0.02)
                    
                # 2) something is close on the right but not on the left    
                elif self.obstacle_right_close and not self.obstacle_left_close:
                    message+="state1:close obstacle right\n"

                    #We adapt our speed to the current one
                    velocity.linear.x=self.smooth_x_speed_target(0.0,0.02)

                    #is there something far on the left ?    
                    if not self.obstacle_full_left_far:                                      #if not the robot turn to the left
                        velocity.angular.z = self.smooth_z_speed_target(base_angular_speed,0.1) #rad/s
                    if velocity.angular.z==0:
                        velocity.angular.z=self.smooth_z_speed_target(base_angular_speed,0.1)

                # 3) something is close on the left but not on the right        
                elif self.obstacle_left_close and not self.obstacle_right_close:
                    message+="state2:close obstacle left\n"

                    #We adapt our speed to the current one              
                    velocity.linear.x=self.smooth_x_speed_target(0.0,0.02)

                    #is there something far on the right ?     
                    if not self.obstacle_full_right_far:                                     #if not the robot turn to the right
                        velocity.angular.z = self.smooth_z_speed_target(-base_angular_speed,0.1) #rad/s
                    if velocity.angular.z==0:
                        velocity.angular.z=self.smooth_z_speed_target(-base_angular_speed,0.1)

                if velocity.linear.x<0.0:velocity.linear.x=0.0                               #avoiding errors

            #================================#
            # Fourth case : something is far #
            #================================#
            elif self.obstacle_right_far or self.obstacle_left_far:
                #We look at the situation (where are the obstacles) and we choose where to move

                # 1) something is far on the right but not on the left  
                if self.obstacle_right_far and not self.obstacle_left_far:
                    message+="state4:far obstacle right\n"

                    #the robot goes to the linear speed of 0.2 smoothly
                    velocity.linear.x=self.smooth_x_speed_target(0.18,0.02)

                    #the angle is adapted to the distance (the closer the obstacle is, the greater is the angle)
                    velocity.angular.z = self.smooth_z_speed_target(-0.83*self.mindistance+1.55,0.1) #rad/s                    the robot goes to the left
    
                # 2) something is far on the left but not on the right  
                elif self.obstacle_left_far and not self.obstacle_right_far:
                    message+="state5:far obstacle left\n"

                    #the robot goes to the linear speed of 0.2 smoothly
                    velocity.linear.x=self.smooth_x_speed_target(0.18,0.02)

                    #the angle is adapted to the distance (the closer the obstacle is, the greater is the angle)
                    velocity.angular.z = self.smooth_z_speed_target(-(-0.83*self.mindistance+1.55),0.1) #rad/s                   the robot goes to the right

                # 3) something is far both on the right and the left
                
                elif self.obstacle_right_far and self.obstacle_left_far:
                    message+="state6:far obstacle both directions\n"

                    #there is something at 90 degres on the left and not on the right
                    if self.obstacle_full_left_far and not self.obstacle_full_right_far:
                        velocity.angular.z = self.smooth_x_speed_target(-0.2,0.02) #rad/s                            the robot goes to the right
                    
                    #there is something at 90 degres on the right and not on the left
                    if self.obstacle_full_right_far and not self.obstacle_full_left_far:
                        velocity.angular.z=self.smooth_x_speed_target(0.2,0.02) #rad/s                               the robot goes to the left

                    #there is something at 90 degres on the right and the left
                    if self.obstacle_full_right_far and self.obstacle_full_left_far:
                        if self.full_right_min<self.full_left_min:
                            velocity.angular.z=self.smooth_z_speed_target(base_angular_speed,0.1) #rad/s                           the robot goes to the left
                        else:
                            velocity.angular.z = self.smooth_z_speed_target(-base_angular_speed,0.1) #rad/s                        the robot goes to the right
                    velocity.linear.x=self.smooth_x_speed_target(0.15,0.03)
                    #the robot goes to the linear speed of 0.15 smoothly
                    
            #===================================#
            # Fifth case : no obstacle in front #
            #===================================#
            else:
                #the robot goes forward
                message+="state 0:no obstacles\n"
                velocity.angular.z = 0.0#rad/s
                velocity.linear.x=self.smooth_x_speed_target(0.55,0.015)    

            #previous values
            self.previous_z=velocity.angular.z
            self.previous_x=velocity.linear.x

            #publishing
            self._pubVelocity.publish(velocity)

            #=============================#
            # Print the current situation #
            #=============================#
            #printing if there are obstacles and where and the current linear and rotative speeds
            message+=str(self.obstacle_left_far)+","+str(self.obstacle_right_far)+"\n"+str(self.obstacle_left_close)+","+str(self.obstacle_right_close)+"\n"+str(self.obstacle_full_left_far)+","+str(self.obstacle_full_right_far)+"\n"+"speed:"+str(self.previous_x)+"    rotation:"+str(self.previous_z)
            message+="\n|----------------|"
            self.log_msg_data=message

    #~~~~~~~~~~~~~~~~~~~~~~#
    # If a goal is defined #
    #~~~~~~~~~~~~~~~~~~~~~~#

    def control_callback_move_to(self):
        #Reactive reaction to environment
        if not self.random_turning:                                                        #if the robot isn't in a random turn
            #self._logger.info( '< define control' )
            velocity=Twist()
            velocity.angular.z = self.previous_z #rad/s
            base_angular_speed=0.7                                                         #rotation speed
            message="\n#----------------#\n"

            #=================================#
            # First case : nothing is scanned #
            #=================================#
            if self.no_scan or self._emergency_stop:                                       #if nothing is scanned, the robot stop
                message+="no scan/emergency stop"
                velocity.linear.x = 0.0 #m/s
                velocity.angular.z = 0.0 #rad/s

            elif self.distance_goal<0.1:
                message+='goal atteint'
                velocity.linear.x = 0.0 #m/s
                velocity.angular.z = 0.0 #rad/s                                            #the robot stop              

            #======================================#
            # Second case : something is too close #
            #======================================#
            elif self.totalmindistance<0.2:                                                #if an object is too close, the robot can only rotate on itself
                message+="object to close, turning around\n"
                velocity.linear.x = 0.0 #m/s
                velocity.angular.z  = 0.5
            elif self.totalmindistance_right<0.25 and self.totalmindistance_left<0.25:
                velocity.linear.x= self.smooth_x_speed_target(-0.2,0.02)
                velocity.angular.z  = 0.0 #m/s
            elif self.totalmindistance_right<0.25:
                message+="object to close on the right, turning around on the left\n"
                velocity.linear.x = 0.0 #m/s
                velocity.angular.z  = self.smooth_z_speed_target(0.5,0.1)
            elif self.totalmindistance_left<0.25:
                message+="object to close on the left, turning around on the right\n"
                velocity.linear.x = 0.0 #m/s
                velocity.angular.z  = self.smooth_z_speed_target(-0.5,0.1)
            #=================================#
            # Third case : something is close #
            #=================================#
            elif self.obstacle_right_close or self.obstacle_left_close:                    #something is close
                #We look at the situation (where are the obstacles) and we choose where to move

                # 1) something is close both on the right and on the left
                if self.obstacle_right_close and self.obstacle_left_close:                  
                    message+="state3:close obstacle both directions:"

                    # is there an obstacle 90° far ?
                    if self.obstacle_full_left_far and not self.obstacle_full_right_far:    #also there is something far on the right but not on the left
                        message+="choosed to go right\n"                                    #so the robot go to the right
                        velocity.angular.z = self.smooth_z_speed_target(-base_angular_speed,0.1) #rad/s 
                    if self.obstacle_full_right_far and not self.obstacle_full_left_far:    #also there is something far on the left but not on the right
                        message+="choosed to go left\n"                                     #so the robot go to the left
                        velocity.angular.z=self.smooth_z_speed_target(base_angular_speed,0.1)
                    #We adapt our speed to the current one
                    if velocity.angular.z==0:                                               #if its the first turn and there is not one far side triggered, the robot go to the left
                        velocity.angular.z=self.smooth_z_speed_target(base_angular_speed,0.1)                  
                    
                    velocity.linear.x=self.smooth_x_speed_target(0.0,0.025)
                    
                # 2) something is close on the right but not on the left    
                elif self.obstacle_right_close and not self.obstacle_left_close:
                    message+="state1:close obstacle right\n"

                    #We adapt our speed to the current one

                    velocity.linear.x=self.smooth_x_speed_target(0.15,0.02)


                    #is there something far on the left ?    
                    if not self.obstacle_full_left_far:                                      #if not the robot turn to the left
                        velocity.angular.z = self.smooth_z_speed_target(base_angular_speed,0.1) #rad/s
                    if velocity.angular.z==0:
                        velocity.angular.z=self.smooth_z_speed_target(base_angular_speed,0.1)

                # 3) something is close on the left but not on the right        
                elif self.obstacle_left_close and not self.obstacle_right_close:
                    message+="state2:close obstacle left\n"

                    #We adapt our speed to the current one              

                    velocity.linear.x=self.smooth_x_speed_target(0.15,0.02)

                    #is there something far on the right ?     
                    if not self.obstacle_full_right_far:                                     #if not the robot turn to the right
                        velocity.angular.z = self.smooth_z_speed_target(-base_angular_speed,0.1) #rad/s
                    if velocity.angular.z==0:
                        velocity.angular.z=self.smooth_z_speed_target(-base_angular_speed,0.1)

                if velocity.linear.x<0.0:velocity.linear.x=0.0                             #avoiding errors

            #================================#
            # Fourth case : something is far #
            #================================#
            elif self.obstacle_right_far or self.obstacle_left_far:
                #We look at the situation (where are the obstacles) and we choose where to move

                # 1) something is far on the right but not on the left  
                if self.obstacle_right_far and not self.obstacle_left_far:
                    message+="state4:far obstacle right\n"

                    #the robot goes to the linear speed of 0.2 smoothly
                    velocity.linear.x=self.smooth_x_speed_target(0.18,0.02)

                    #the angle is adapted to the distance (the closer the obstacle is, the greater is the angle)
                    velocity.angular.z = self.smooth_z_speed_target(-0.83*self.mindistance+1.55 ,0.1)#rad/s                    the robot goes to the left
    
                # 2) something is far on the left but not on the right  
                elif self.obstacle_left_far and not self.obstacle_right_far:
                    message+="state5:far obstacle left\n"

                    #the robot goes to the linear speed of 0.2 smoothly
                    velocity.linear.x=self.smooth_x_speed_target(0.18,0.02)

                    #the angle is adapted to the distance (the closer the obstacle is, the greater is the angle)
                    velocity.angular.z = self.smooth_z_speed_target(-(-0.83*self.mindistance+1.55),0.1) #rad/s                   the robot goes to the right

                # 3) something is far both on the right and the left
                
                elif self.obstacle_right_far and self.obstacle_left_far:
                    message+="state6:far obstacle both directions\n"

                    #there is something at 90 degres on the left and not on the right
                    if self.obstacle_full_left_far and not self.obstacle_full_right_far:
                        velocity.angular.z = self.smooth_z_speed_target(-base_angular_speed,0.1) #rad/s                            the robot goes to the right
                    
                    #there is something at 90 degres on the right and not on the left
                    if self.obstacle_full_right_far and not self.obstacle_full_left_far:
                        velocity.angular.z=self.smooth_z_speed_target(base_angular_speed,0.1) #rad/s                               the robot goes to the left

                    #there is something at 90 degres on the right and the left
                    if self.obstacle_full_right_far and self.obstacle_full_left_far:
                        if self.full_right_min<self.full_left_min:
                            velocity.angular.z=self.smooth_z_speed_target(base_angular_speed,0.1) #rad/s                           the robot goes to the left
                        else:
                            velocity.angular.z = self.smooth_z_speed_target(-base_angular_speed,0.1) #rad/s                        the robot goes to the right
                    velocity.linear.x=self.smooth_x_speed_target(0.12,0.02)
                    #the robot goes to the linear speed of 0.15 smoothly
            
            #===============================================#
            # Fifth case : the goal can be reached directly #
            #===============================================#
            elif not (self.goal_straight_line_obstacle or self.goal_obstacle_right_far or self.goal_obstacle_left_far): #si rien vers le goal
                message+="state7 : le goal est libre d'accès:"
                if abs(self.theta_goal)>0.08726: #si pas bien oriente
                    velocity.angular.z = self.orientate_to_goal() #s'oriente vers le goal
                    velocity.linear.x = self.smooth_x_speed_target(0.0,0.02) #m/s
                    message+="le goal n'est pas directement en face, turning on himself\n"
                else:#si bien oriente
                    velocity.linear.x=self.smooth_x_speed_target(self.speed_to_goal(self.distance_goal),0.02)#go vers le goal
                    message+="le goal est en face, going forward\n"
    
            #===================================#
            # Sixth case : no obstacle in front #
            #===================================#
            else:
                #the robot goes forward
                velocity.angular.z = self.orientate_to_goal()#rad/s
                velocity.linear.x=self.smooth_x_speed_target(0.55,0.012)
                message+="state 0:no obstacles\n"
            
            #previous values
            self.previous_z=velocity.angular.z
            self.previous_x=velocity.linear.x

            #publishing
            self._pubVelocity.publish(velocity)

            #=============================#
            # Print the current situation #
            #=============================#
            #printing if there are obstacles and where and the current linear and rotative speeds
            message+=str(self.obstacle_left_far)+","+str(self.obstacle_right_far)+"\n"+str(self.obstacle_left_close)+","+str(self.obstacle_right_close)+"\n"+str(self.obstacle_full_left_far)+","+str(self.obstacle_full_right_far)+"\n"+"speed:"+str(self.previous_x)+"    rotation:"+str(self.previous_z)+"\n"
            message+="capteur vers goal"+str(self.goal_obstacle_left_far)+str(self.goal_straight_line_obstacle)+str(self.goal_obstacle_right_far)+"\n"
            #the message is printed only if it is different from the previous one
            message+="|----------------|"
            self.log_msg_data=message

    # speed function, with the previous x and z stored variables
    def smooth_x_speed_target(self,target:float,step:float):
        if self.previous_x>target+15*step:                                          #if the robot was moving fast, it slows hardly
            velocity_value=self.previous_x -step*2
        elif self.previous_x>target+step:                                            #if the robot was moving slow, its slow softly
            velocity_value=self.previous_x -step
        elif self.previous_x<target-step:
            velocity_value=self.previous_x +step
        else:                                                                   #if the robot was not moving, it continue
            velocity_value=target
        return(velocity_value)
    def smooth_z_speed_target(self,target:float,step:float):
        if self.previous_z>target+15*step:                                          #if the robot was moving fast, it slows hardly
            velocity_value=self.previous_z -step*2
        elif self.previous_z>target+step:                                            #if the robot was moving slow, its slow softly
            velocity_value=self.previous_z -step
        elif self.previous_z<target-step:
            velocity_value=self.previous_z +step
        else:                                                                   #if the robot was not moving, it continue
            velocity_value=target
        return(velocity_value)    
    #random turn functions callback
    def random_turn(self):
        if not self._emergency_stop and not self.move_to_command :
            velocity=Twist()
            self.random_turning=True
            direction=rd.randint(1,2)                                                      #right or left ?
            angle_value=rd.randint(30,180)                                                 #angle ? (betwenn 30 and 180°)
            if direction==1:angle=-angle_value
            if direction==2:angle=angle_value
            while self.previous_x>0.0 and not self._emergency_stop:
                velocity.linear.x=self.smooth_x_speed_target(0.0,0.03)
                self.previous_x=velocity.linear.x
                self._pubVelocity.publish(velocity)
            log_msg=String()
            log_msg.data="Tour aléatoire : je commence un tour d'un angle de"+str(angle)+"degrès"
            self._pubLoggerMsg.publish(log_msg)
            self.turn_by_given_angle(angle,0.7)
            while self.previous_x<0.1 and not self._emergency_stop:
                velocity.linear.x=self.smooth_x_speed_target(0.5,0.02)
                self.previous_x=velocity.linear.x
                self._pubVelocity.publish(velocity)
            self.random_turning=False

    def turn_by_given_angle(self,deg,angular_speed):
        velocity=Twist()
        deg_per_sec=angular_speed*180/3.14
        duration=abs(deg/deg_per_sec) - 0.25
        if deg<0:
            rotation_speed=-angular_speed
        else:
            rotation_speed=angular_speed
        start = time()
        counter=0
        while counter < duration and not self._emergency_stop: 
            velocity.angular.z = rotation_speed
            counter = time()-start

            #Previous values
            self.previous_z=velocity.angular.z
            
            #Publish
            self._pubVelocity.publish(velocity)
    
    # Speed when going to the goal
    def speed_to_goal(self,distance):
        speed=distance*0.7
        if speed>0.7:speed=0.7
        if distance <0.05:speed=0
        return(speed)

    # Orientation to the goal
    def orientate_to_goal(self):
        precision=0.08726
        if self.theta_goal>precision*3:
            rad_speed=0.7
        elif self.theta_goal<-precision*3:
            rad_speed=-0.7
    
        elif self.theta_goal>precision:
            rad_speed=0.3
        elif self.theta_goal<-precision:
            rad_speed=-0.3
        else:
            rad_speed=0.0
        return(rad_speed)
       
# Go:
if __name__ == '__main__' :
    main()